### PR TITLE
Medium: Surface Reaction Class 

### PR DESCRIPTION
**Pull request by pithonas**

### CODE REVIEW

**Comment by nixeimar** [comment]
Thanks pithonas.

**Comment by pithonas** [comment]
Dear Prof. N. Cheimarios

Your are welcome

I would like to express my interest on this project.
I am diploma thesis student in the Condensed Matter Physics section at
National and Kapodistrian University
of Athens. My interest is in Computational Physics and Statistical Physics.

Kind Regards,
Tasos



Στις Δευ, 9 Μαρ 2020 στις 9:55 π.μ., ο/η Nikolaos (Nikos) Cheimarios <
notifications@github.com> έγραψε:

**Comment by nixeimar** [comment]
Dear Tasos,

I am very glad that you are interest in Apothesis project.
Is it possible to send me your recent CV?

Also there is an open discussion on the projects of GeomScale - 
including Apothesis here:
https://gitter.im/GeomScale/community#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

You are very welcome to join the conversations.

Best,
Nikos

P.S. I am not a Prof. Please just call me Nikos.

Στις 09/03/2020 23:58, pithonas έγραψε:

**Comment by pithonas** [comment]
Dear Nikos

Thank you for your reply and for the links.

Kind regards
Tasos

Στις Τρί, 10 Μαρ 2020 στις 11:33 π.μ., ο/η Nikolaos (Nikos) Cheimarios <
notifications@github.com> έγραψε:

**Pull request merged**
